// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace IMS
{
    [Table("Admin")]
    public partial class Admin
    {
        [Key]
        public int AdminId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Aname { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Ausername { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Apassword { get; set; }
    }
}